[package]
name = "event-platform_backend"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.8"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "1.4.5", features = ["postgres", "chrono"] }
chrono = "0.4"
